# ===================================
# TappPlus - Unified Docker Compose
# Single container with Nginx + API + Web + Worker + Redis
# ===================================

version: '3.8'

services:
  # ===================================
  # TappPlus Application (All-in-One)
  # ===================================
  tappplus:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tappplus-app
    restart: unless-stopped

    environment:
      # Node Environment
      NODE_ENV: production

      # Database Configuration (SQLite)
      DATABASE_URL: file:/app/data/meditache.db

      # Redis Configuration (localhost since it's in the same container)
      REDIS_URL: redis://127.0.0.1:6379

      # JWT Secrets (CHANGE THESE IN PRODUCTION!)
      JWT_SECRET: ${JWT_SECRET:-your-super-secret-jwt-key-change-in-production}
      JWT_REFRESH_SECRET: ${JWT_REFRESH_SECRET:-your-super-secret-refresh-key-change-in-production}

      # Timezone
      TZ: ${TZ:-Africa/Douala}

      # API Configuration
      API_PORT: 5550

      # Web Configuration
      WEB_PORT: 5500
      NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL:-}

    ports:
      - "${HTTP_PORT:-80}:80"  # Nginx reverse proxy (only exposed port)
      # Internal ports (not exposed):
      # - 5500: Web Frontend
      # - 5550: API Backend
      # - 6379: Redis

    volumes:
      # Persist SQLite database
      - tappplus_data:/app/data

      # Persist PM2 logs
      - tappplus_logs:/app/logs

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      start_period: 40s
      retries: 3

    # Resource limits (optional - adjust based on your server)
    # deploy:
    #   resources:
    #     limits:
    #       cpus: '2'
    #       memory: 2G
    #     reservations:
    #       cpus: '1'
    #       memory: 1G

# ===================================
# Volumes
# ===================================
volumes:
  # SQLite database storage
  tappplus_data:
    driver: local

  # Application logs
  tappplus_logs:
    driver: local

# ===================================
# Networks (optional)
# ===================================
networks:
  default:
    driver: bridge
